name: duq
channels:
    - pytorch
    - defaults
dependencies:
    - python>=3.8
    - pytorch
    - torchvision
    - cudatoolkit
    - ignite
    - tqdm
    - tensorboard
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
    - h5py
